"""init content tables

Revision ID: 0001
Revises:
Create Date: 2026-05-20 00:00:00.000000

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modules",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("author_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("manager_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')",
            name="modules_status_check",
        ),
    )
    op.create_index("idx_modules_author", "modules", ["author_id"])
    op.create_index("idx_modules_manager", "modules", ["manager_id"])
    op.create_index("idx_modules_status", "modules", ["status"])

    op.create_table(
        "lessons",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "module_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "order_index", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("r7_uri", sa.Text(), nullable=False),
        sa.Column("author_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["module_id"], ["modules.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("module_id", "order_index"),
    )
    op.create_index("idx_lessons_module", "lessons", ["module_id"])

    op.create_table(
        "heuristics",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "module_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column("author_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "manager_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "is_approved",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["module_id"], ["modules.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_heuristics_module", "heuristics", ["module_id"])
    op.create_index("idx_heuristics_manager", "heuristics", ["manager_id"])
    op.create_index(
        "idx_heuristics_approved", "heuristics", ["is_approved"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_heuristics_approved", table_name="heuristics")
    op.drop_index("idx_heuristics_manager", table_name="heuristics")
    op.drop_index("idx_heuristics_module", table_name="heuristics")
    op.drop_table("heuristics")
    op.drop_index("idx_lessons_module", table_name="lessons")
    op.drop_table("lessons")
    op.drop_index("idx_modules_status", table_name="modules")
    op.drop_index("idx_modules_manager", table_name="modules")
    op.drop_index("idx_modules_author", table_name="modules")
    op.drop_table("modules")
    # ### end Alembic commands ###
