"""Fix invitations.created_by nullable and add ondelete SET NULL to FKs

Revision ID: 7b914f7320f2
Revises: b0e634e92ba9
Create Date: 2026-05-20 04:08:26.973534

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b914f7320f2"
down_revision: str | Sequence[str] | None = "b0e634e92ba9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("invitations", "created_by",
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f("invitations_created_by_fkey"), "invitations", type_="foreignkey")
    op.create_foreign_key(None, "invitations", "users", ["created_by"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "invitations", type_="foreignkey")
    op.create_foreign_key(
        op.f("invitations_created_by_fkey"),
        "invitations",
        "users",
        ["created_by"],
        ["id"],
    )
    op.alter_column("invitations", "created_by",
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
