"""remove roles table, add role column to users and invitations

Revision ID: b0e634e92ba9
Revises: f39b5659de8b
Create Date: 2026-05-20 00:13:13.582704

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0e634e92ba9"
down_revision: Union[str, Sequence[str], None] = "f39b5659de8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE user_roles CASCADE")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.execute("DROP TABLE roles CASCADE")
    op.add_column(
        "invitations",
        sa.Column("role_name", sa.String(length=50), nullable=False),
    )
    op.drop_column("invitations", "role_id")
    op.add_column(
        "users", sa.Column("role", sa.String(length=50), nullable=False)
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_column("users", "role")
    op.add_column(
        "invitations",
        sa.Column(
            "role_id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "invitations_role_id_fkey",
        "invitations",
        "roles",
        ["role_id"],
        ["id"],
    )
    op.drop_column("invitations", "role_name")
    op.create_table(
        "roles",
        sa.Column(
            "id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "name",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="roles_pkey"),
    )
    op.create_index(
        op.f("ix_roles_name"), "roles", ["name"], unique=True
    )
    op.create_table(
        "user_roles",
        sa.Column(
            "user_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "role_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name="user_roles_role_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="user_roles_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "role_id", name="user_roles_pkey"
        ),
    )
    # ### end Alembic commands ###
