"""Add invitations and user hierarchy

Revision ID: f39b5659de8b
Revises: e5e5c39e9830
Create Date: 2026-05-19 17:32:50.377542

"""
from collections.abc import Sequence
from datetime import UTC, datetime
from uuid import uuid4

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f39b5659de8b"
down_revision: str | Sequence[str] | None = "e5e5c39e9830"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ROLE_NAMES = ["admin", "methodist", "seminarist", "candidate"]


def upgrade() -> None:
    """Add invitations table, user hierarchy columns, and seed roles."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Seed roles
    roles_table = sa.table(
        "roles",
        sa.column("id", postgresql.UUID(as_uuid=True)),
        sa.column("name", sa.String(50)),
        sa.column("description", sa.String(255)),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    now = datetime.now(UTC)
    op.bulk_insert(
        roles_table,
        [
            {
                "id": str(uuid4()),
                "name": name,
                "description": f"{name.capitalize()} role",
                "created_at": now,
            }
            for name in ROLE_NAMES
        ],
    )

    # Add manager_id and invited_by to users
    op.add_column(
        "users",
        sa.Column(
            "manager_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id"),
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "invited_by",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id"),
            nullable=True,
        ),
    )

    # Create invitations table
    op.create_table(
        "invitations",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token", sa.String(255), nullable=False),
        sa.Column("email", sa.String(255), nullable=True),
        sa.Column(
            "role_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("roles.id"),
            nullable=False,
        ),
        sa.Column(
            "manager_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id"),
            nullable=True,
        ),
        sa.Column(
            "created_by",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id"),
            nullable=False,
        ),
        sa.Column("used", sa.Boolean(), default=False, nullable=False),
        sa.Column(
            "used_by",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id"),
            nullable=True,
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invitations_token"), "invitations", ["token"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove invitations table, user hierarchy columns, and seeded roles."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_invitations_token"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_column("users", "invited_by")
    op.drop_column("users", "manager_id")

    # Remove seeded roles
    op.execute("DELETE FROM roles WHERE name IN ('admin', 'methodist', 'seminarist', 'candidate')")

    # ### end Alembic commands ###
